In [1]:
import numpy as np
import pandas as pd

In [2]:
pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\windows\anaconda3\lib\site-packages (2.17.0)
Requirement already satisfied: tensorflow-intel==2.17.0 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow) (2.17.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (0.2.0)
Requirement already satisfied: h5py>=3.10.0 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (3.11.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (18.1.1)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.3.1 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (0.4.0)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (3.3.0)
Requirement already satisfied: packaging in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (23.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (3.20.3)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (2.32.2)
Requirement already satisfied: setuptools in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (69.5.1)
Requirement already satisfied: six>=1.12.0 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (4.11.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (1.65.4)
Requirement already satisfied: tensorboard<2.18,>=2.17 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (2.17.0)
Requirement already satisfied: keras>=3.2.0 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (3.4.1)
Requirement already satisfied: numpy<2.0.0,>=1.26.0 in c:\users\windows\anaconda3\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (1.26.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\windows\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.17.0->tensorflow) (0.43.0)
Requirement already satisfied: rich in c:\users\windows\anaconda3\lib\site-packages (from keras>=3.2.0->tensorflow-intel==2.17.0->tensorflow) (13.3.5)
Requirement already satisfied: namex in c:\users\windows\anaconda3\lib\site-packages (from keras>=3.2.0->tensorflow-intel==2.17.0->tensorflow) (0.0.8)
Requirement already satisfied: optree in c:\users\windows\anaconda3\lib\site-packages (from keras>=3.2.0->tensorflow-intel==2.17.0->tensorflow) (0.12.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\windows\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.17.0->tensorflow) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\windows\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.17.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\windows\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.17.0->tensorflow) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\windows\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.17.0->tensorflow) (2024.7.4)
Requirement already satisfied: markdown>=2.6.8 in c:\users\windows\anaconda3\lib\site-packages (from tensorboard<2.18,>=2.17->tensorflow-intel==2.17.0->tensorflow) (3.4.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\windows\anaconda3\lib\site-packages (from tensorboard<2.18,>=2.17->tensorflow-intel==2.17.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\windows\anaconda3\lib\site-packages (from tensorboard<2.18,>=2.17->tensorflow-intel==2.17.0->tensorflow) (3.0.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\windows\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.18,>=2.17->tensorflow-intel==2.17.0->tensorflow) (2.1.3)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\users\windows\anaconda3\lib\site-packages (from rich->keras>=3.2.0->tensorflow-intel==2.17.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\windows\anaconda3\lib\site-packages (from rich->keras>=3.2.0->tensorflow-intel==2.17.0->tensorflow) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\windows\anaconda3\lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich->keras>=3.2.0->tensorflow-intel==2.17.0->tensorflow) (0.1.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
!c:/Users/Windows/AppData/Local/Microsoft/WindowsApps/python3.12.exe -m pip install --upgrade setuptools

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: setuptools in c:\users\windows\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (75.0.0)
Collecting setuptools
  Downloading setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
Downloading setuptools-75.1.0-py3-none-any.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------- ----------------------- 0.5/1.2 MB 2.8 MB/s eta 0:00:01
   --------------------------------- ------ 1.0/1.2 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 2.3 MB/s eta 0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 75.0.0
    Uninstalling setuptools-75.0.0:
      Successfully uninstalled setuptools-75.0.0
Successfully installed setuptools-75.1.0

In [4]:
import distutils

In [5]:
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
import tensorflow.keras as k

from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
import time
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder

In [6]:
time_domain_features_train = pd.read_csv("C:/Users/Windows/Downloads/train&test/time_domain_features_train.csv")
time_domain_features_train.head()

,MEAN_RR,MEDIAN_RR,SDRR,RMSSD,SDSD,SDRR_RMSSD,HR,pNN25,pNN50,KURT,SKEW,MEAN_REL_RR,MEDIAN_REL_RR,SDRR_REL_RR,RMSSD_REL_RR,SDSD_REL_RR,SDRR_RMSSD_REL_RR,KURT_REL_RR,SKEW_REL_RR,uuid
0,885.157845,853.763730,140.972741,15.554505,15.553371,9.063146,69.499952,11.133333,0.533333,-0.856554,0.335218,-0.000203,-0.000179,0.017080,0.007969,0.007969,2.143342,-0.856554,0.335218,89df2855-56eb-4706-a23b-b39363dd605a
1,939.425371,948.357865,81.317742,12.964439,12.964195,6.272369,64.363150,5.600000,0.000000,-0.408190,-0.155286,-0.000059,0.000611,0.013978,0.004769,0.004769,2.930855,-0.408190,-0.155286,80c795e4-aa56-4cc0-939c-19634b89cbb2
2,898.186047,907.006860,84.497236,16.305279,16.305274,5.182201,67.450066,13.066667,0.200000,0.351789,-0.656813,-0.000011,-0.000263,0.018539,0.008716,0.008716,2.127053,0.351789,-0.656813,c2d5d102-967c-487d-88f2-8b005a449f3e
3,881.757865,893.460030,90.370537,15.720468,15.720068,5.748591,68.809562,11.800000,0.133333,-0.504947,-0.386138,0.000112,0.000494,0.017761,0.008660,0.008660,2.050988,-0.504947,-0.386138,37eabc44-1349-4040-8896-0d113ad4811f
4,809.625331,811.184865,62.766242,19.213819,19.213657,3.266724,74.565728,20.200000,0.200000,-0.548408,-0.154252,-0.000100,-0.002736,0.023715,0.013055,0.013055,1.816544,-0.548408,-0.154252,aa777a6a-7aa3-4f6e-aced-70f8691dd2b7

In [7]:
heart_rate_non_linear_features_train = pd.read_csv("C:/Users/Windows/Downloads/train&test/heart_rate_non_linear_features_train.csv")
heart_rate_non_linear_features_train.head()

,uuid,SD1,SD2,sampen,higuci,datasetId,condition
0,89df2855-56eb-4706-a23b-b39363dd605a,11.001565,199.061782,2.139754,1.163485,2,no stress
1,80c795e4-aa56-4cc0-939c-19634b89cbb2,9.170129,114.634458,2.174499,1.084711,2,interruption
2,c2d5d102-967c-487d-88f2-8b005a449f3e,11.533417,118.939253,2.135350,1.176315,2,interruption
3,37eabc44-1349-4040-8896-0d113ad4811f,11.119476,127.318597,2.178341,1.179688,2,no stress
4,aa777a6a-7aa3-4f6e-aced-70f8691dd2b7,13.590641,87.718281,2.221121,1.249612,2,no stress

In [8]:
frequency_domain_features_train = pd.read_csv("C:/Users/Windows/Downloads/train&test/frequency_domain_features_train.csv")
frequency_domain_features_train.head()

,uuid,VLF,VLF_PCT,LF,LF_PCT,LF_NU,HF,HF_PCT,HF_NU,TP,LF_HF,HF_LF
0,89df2855-56eb-4706-a23b-b39363dd605a,2661.894136,72.203287,1009.249419,27.375666,98.485263,15.522603,0.421047,1.514737,3686.666157,65.018055,0.015380
1,80c795e4-aa56-4cc0-939c-19634b89cbb2,2314.265450,76.975728,690.113275,22.954139,99.695397,2.108525,0.070133,0.304603,3006.487251,327.296635,0.003055
2,c2d5d102-967c-487d-88f2-8b005a449f3e,1373.887112,51.152225,1298.222619,48.335104,98.950472,13.769729,0.512671,1.049528,2685.879461,94.280910,0.010607
3,37eabc44-1349-4040-8896-0d113ad4811f,2410.357408,70.180308,1005.981659,29.290305,98.224706,18.181913,0.529387,1.775294,3434.520980,55.328701,0.018074
4,aa777a6a-7aa3-4f6e-aced-70f8691dd2b7,1151.177330,43.918366,1421.782051,54.242160,96.720007,48.215822,1.839473,3.279993,2621.175204,29.487873,0.033912

In [9]:
time_domain_features_test = pd.read_csv("C:/Users/Windows/Downloads/train&test/time_domain_features_test.csv")
time_domain_features_test.head()

,MEAN_RR,MEDIAN_RR,SDRR,RMSSD,SDSD,SDRR_RMSSD,pNN25,pNN50,KURT,SKEW,MEAN_REL_RR,MEDIAN_REL_RR,SDRR_REL_RR,RMSSD_REL_RR,SDSD_REL_RR,SDRR_RMSSD_REL_RR,KURT_REL_RR,SKEW_REL_RR,uuid
0,934.665288,939.03173,82.139495,11.801781,11.801772,6.959924,3.933333,0.133333,-0.680262,-0.233075,0.000016,0.000288,0.012933,0.004578,0.004578,2.825038,-0.680262,-0.233075,62b75db5-bc40-4c8f-9166-daf0efcab4c2
1,817.062380,816.33879,55.492332,20.558810,20.558768,2.699200,24.600000,0.533333,-0.034454,-0.051689,0.000040,-0.002749,0.025148,0.013921,0.013921,1.806517,-0.034454,-0.051689,a99549ad-3eb6-4413-bc90-9053e7f7e684
2,876.762022,894.19889,88.690820,13.853737,13.853730,6.401942,7.066667,0.533333,-0.206953,-0.589940,0.000010,-0.000172,0.015533,0.008149,0.008149,1.906180,-0.206953,-0.589940,cb573d3a-c767-4556-b32e-ad8c08ded214
3,1038.640693,998.91429,213.725850,16.457194,16.454801,12.986774,10.800000,1.866667,-0.820407,0.487198,-0.000238,-0.000464,0.016882,0.007587,0.007587,2.225116,-0.820407,0.487198,47a0c6de-2aef-4ac3-997d-252fa6fd07f1
4,774.548508,778.90508,51.577855,10.273114,10.273049,5.020664,2.000000,0.066667,1.738453,-0.005082,0.000054,-0.000006,0.013479,0.007811,0.007811,1.725606,1.738453,-0.005082,de3fd54f-c74e-4fe8-bf2a-7a127f68b312

In [10]:
heart_rate_non_linear_features_test = pd.read_csv("C:/Users/Windows/Downloads/train&test/heart_rate_non_linear_features_test.csv")
heart_rate_non_linear_features_test.head()

,uuid,SD1,SD2,sampen,higuci,datasetId,condition
0,62b75db5-bc40-4c8f-9166-daf0efcab4c2,8.347898,115.862444,2.209659,1.100715,2,time pressure
1,a99549ad-3eb6-4413-bc90-9053e7f7e684,14.542096,77.118903,2.186132,1.290615,2,no stress
2,cb573d3a-c767-4556-b32e-ad8c08ded214,9.799336,125.044377,2.051571,1.226663,2,no stress
3,47a0c6de-2aef-4ac3-997d-252fa6fd07f1,11.639185,302.029812,2.080910,1.085143,2,time pressure
4,de3fd54f-c74e-4fe8-bf2a-7a127f68b312,7.266567,72.579248,2.068728,1.252547,2,interruption

In [11]:
frequency_domain_features_test = pd.read_csv("C:/Users/Windows/Downloads/train&test/frequency_domain_features_test.csv")
frequency_domain_features_test.head()

,uuid,VLF,VLF_PCT,LF,LF_PCT,LF_NU,HF,HF_PCT,HF_NU,TP,LF_HF,HF_LF
0,62b75db5-bc40-4c8f-9166-daf0efcab4c2,1868.532278,76.511189,570.643114,23.366245,99.478197,2.993254,0.122565,0.521803,2442.168645,190.643094,0.005245
1,a99549ad-3eb6-4413-bc90-9053e7f7e684,568.742845,26.301350,1553.971621,71.862973,97.509212,39.694850,1.835677,2.490788,2162.409316,39.147940,0.025544
2,cb573d3a-c767-4556-b32e-ad8c08ded214,2101.871207,75.836461,655.175895,23.639042,97.829386,14.536877,0.524497,2.170614,2771.583978,45.069921,0.022188
3,47a0c6de-2aef-4ac3-997d-252fa6fd07f1,5757.544433,90.562305,592.913021,9.326123,98.817806,7.093235,0.111572,1.182194,6357.550689,83.588517,0.011963
4,de3fd54f-c74e-4fe8-bf2a-7a127f68b312,964.696325,70.256575,374.939530,27.305968,91.805057,33.468834,2.437457,8.194943,1373.104689,11.202647,0.089265

In [12]:
combined_train = pd.concat([time_domain_features_train, frequency_domain_features_train, heart_rate_non_linear_features_train], axis=1)
combined_train.head()

,MEAN_RR,MEDIAN_RR,SDRR,RMSSD,SDSD,SDRR_RMSSD,HR,pNN25,pNN50,KURT,...,TP,LF_HF,HF_LF,uuid,SD1,SD2,sampen,higuci,datasetId,condition
0,885.157845,853.763730,140.972741,15.554505,15.553371,9.063146,69.499952,11.133333,0.533333,-0.856554,...,3686.666157,65.018055,0.015380,89df2855-56eb-4706-a23b-b39363dd605a,11.001565,199.061782,2.139754,1.163485,2,no stress
1,939.425371,948.357865,81.317742,12.964439,12.964195,6.272369,64.363150,5.600000,0.000000,-0.408190,...,3006.487251,327.296635,0.003055,80c795e4-aa56-4cc0-939c-19634b89cbb2,9.170129,114.634458,2.174499,1.084711,2,interruption
2,898.186047,907.006860,84.497236,16.305279,16.305274,5.182201,67.450066,13.066667,0.200000,0.351789,...,2685.879461,94.280910,0.010607,c2d5d102-967c-487d-88f2-8b005a449f3e,11.533417,118.939253,2.135350,1.176315,2,interruption
3,881.757865,893.460030,90.370537,15.720468,15.720068,5.748591,68.809562,11.800000,0.133333,-0.504947,...,3434.520980,55.328701,0.018074,37eabc44-1349-4040-8896-0d113ad4811f,11.119476,127.318597,2.178341,1.179688,2,no stress
4,809.625331,811.184865,62.766242,19.213819,19.213657,3.266724,74.565728,20.200000,0.200000,-0.548408,...,2621.175204,29.487873,0.033912,aa777a6a-7aa3-4f6e-aced-70f8691dd2b7,13.590641,87.718281,2.221121,1.249612,2,no stress

In [13]:
combined_test = pd.concat([time_domain_features_test, frequency_domain_features_test, heart_rate_non_linear_features_test], axis=1)
combined_test.head()

,MEAN_RR,MEDIAN_RR,SDRR,RMSSD,SDSD,SDRR_RMSSD,pNN25,pNN50,KURT,SKEW,...,TP,LF_HF,HF_LF,uuid,SD1,SD2,sampen,higuci,datasetId,condition
0,934.665288,939.03173,82.139495,11.801781,11.801772,6.959924,3.933333,0.133333,-0.680262,-0.233075,...,2442.168645,190.643094,0.005245,62b75db5-bc40-4c8f-9166-daf0efcab4c2,8.347898,115.862444,2.209659,1.100715,2,time pressure
1,817.062380,816.33879,55.492332,20.558810,20.558768,2.699200,24.600000,0.533333,-0.034454,-0.051689,...,2162.409316,39.147940,0.025544,a99549ad-3eb6-4413-bc90-9053e7f7e684,14.542096,77.118903,2.186132,1.290615,2,no stress
2,876.762022,894.19889,88.690820,13.853737,13.853730,6.401942,7.066667,0.533333,-0.206953,-0.589940,...,2771.583978,45.069921,0.022188,cb573d3a-c767-4556-b32e-ad8c08ded214,9.799336,125.044377,2.051571,1.226663,2,no stress
3,1038.640693,998.91429,213.725850,16.457194,16.454801,12.986774,10.800000,1.866667,-0.820407,0.487198,...,6357.550689,83.588517,0.011963,47a0c6de-2aef-4ac3-997d-252fa6fd07f1,11.639185,302.029812,2.080910,1.085143,2,time pressure
4,774.548508,778.90508,51.577855,10.273114,10.273049,5.020664,2.000000,0.066667,1.738453,-0.005082,...,1373.104689,11.202647,0.089265,de3fd54f-c74e-4fe8-bf2a-7a127f68b312,7.266567,72.579248,2.068728,1.252547,2,interruption

In [14]:
combined_train.drop_duplicates()
combined_train
combined_test.drop_duplicates()
combined_test

,MEAN_RR,MEDIAN_RR,SDRR,RMSSD,SDSD,SDRR_RMSSD,pNN25,pNN50,KURT,SKEW,...,TP,LF_HF,HF_LF,uuid,SD1,SD2,sampen,higuci,datasetId,condition
0,934.665288,939.031730,82.139495,11.801781,11.801772,6.959924,3.933333,0.133333,-0.680262,-0.233075,...,2442.168645,190.643094,0.005245,62b75db5-bc40-4c8f-9166-daf0efcab4c2,8.347898,115.862444,2.209659,1.100715,2,time pressure
1,817.062380,816.338790,55.492332,20.558810,20.558768,2.699200,24.600000,0.533333,-0.034454,-0.051689,...,2162.409316,39.147940,0.025544,a99549ad-3eb6-4413-bc90-9053e7f7e684,14.542096,77.118903,2.186132,1.290615,2,no stress
2,876.762022,894.198890,88.690820,13.853737,13.853730,6.401942,7.066667,0.533333,-0.206953,-0.589940,...,2771.583978,45.069921,0.022188,cb573d3a-c767-4556-b32e-ad8c08ded214,9.799336,125.044377,2.051571,1.226663,2,no stress
3,1038.640693,998.914290,213.725850,16.457194,16.454801,12.986774,10.800000,1.866667,-0.820407,0.487198,...,6357.550689,83.588517,0.011963,47a0c6de-2aef-4ac3-997d-252fa6fd07f1,11.639185,302.029812,2.080910,1.085143,2,time pressure
4,774.548508,778.905080,51.577855,10.273114,10.273049,5.020664,2.000000,0.066667,1.738453,-0.005082,...,1373.104689,11.202647,0.089265,de3fd54f-c74e-4fe8-bf2a-7a127f68b312,7.266567,72.579248,2.068728,1.252547,2,interruption
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41028,750.366321,755.151075,82.028613,10.689584,10.688565,7.673695,1.933333,0.000000,-0.011224,-0.243444,...,2237.779643,21.680663,0.046124,11253232-cf0a-4c40-abfb-ac2795effd9b,7.560479,115.759345,2.127188,1.169883,2,no stress
41029,614.675733,595.120315,71.051513,8.695831,8.695537,8.170756,1.866667,0.200000,6.540759,2.438418,...,1744.952487,12.050447,0.082984,38052c36-d08d-4305-905b-830f600ce2b9,6.150725,100.293588,1.569003,1.195527,2,no stress
41030,995.240506,1005.219600,98.196216,21.757512,21.755782,4.513210,25.800000,2.066667,0.973106,-0.681300,...,3720.972447,253.224210,0.003949,8ef3781b-512f-42ce-bcfd-47f5c1070bb0,15.388795,138.015139,2.131040,1.217576,2,interruption
41031,778.333203,786.842895,47.346036,7.532107,7.531970,6.285895,0.400000,0.000000,3.279160,-1.553159,...,552.951041,10.445825,0.095732,2bf689f3-af22-426d-91cf-e9e173ad3a54,5.327684,66.745112,1.949010,1.244982,2,no stress
41032,812.609375,826.359365,153.665263,13.512763,13.510001,11.371861,5.333333,1.266667,0.908939,0.492250,...,2437.764423,13.761861,0.072665,0b654db0-e4d3-4ba3-b9ce-9c9291c8271e,9.556202,217.105285,1.806252,1.174924,2,interruption

In [15]:
combined_train.isnull().sum()
combined_test.isnull().sum()

MEAN_RR              0
MEDIAN_RR            0
SDRR                 0
RMSSD                0
SDSD                 0
SDRR_RMSSD           0
pNN25                0
pNN50                0
KURT                 0
SKEW                 0
MEAN_REL_RR          0
MEDIAN_REL_RR        0
SDRR_REL_RR          0
RMSSD_REL_RR         0
SDSD_REL_RR          0
SDRR_RMSSD_REL_RR    0
KURT_REL_RR          0
SKEW_REL_RR          0
uuid                 0
uuid                 0
VLF                  0
VLF_PCT              0
LF                   0
LF_PCT               0
LF_NU                0
HF                   0
HF_PCT               0
HF_NU                0
TP                   0
LF_HF                0
HF_LF                0
uuid                 0
SD1                  0
SD2                  0
sampen               0
higuci               0
datasetId            0
condition            0
dtype: int64

In [16]:
combined_train.info()
combined_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 369289 entries, 0 to 369288
Data columns (total 39 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   MEAN_RR            369289 non-null  float64
 1   MEDIAN_RR          369289 non-null  float64
 2   SDRR               369289 non-null  float64
 3   RMSSD              369289 non-null  float64
 4   SDSD               369289 non-null  float64
 5   SDRR_RMSSD         369289 non-null  float64
 6   HR                 369289 non-null  float64
 7   pNN25              369289 non-null  float64
 8   pNN50              369289 non-null  float64
 9   KURT               369289 non-null  float64
 10  SKEW               369289 non-null  float64
 11  MEAN_REL_RR        369289 non-null  float64
 12  MEDIAN_REL_RR      369289 non-null  float64
 13  SDRR_REL_RR        369289 non-null  float64
 14  RMSSD_REL_RR       369289 non-null  float64
 15  SDSD_REL_RR        369289 non-null  float64
 16  SDRR_RMSSD_REL_RR  369289 non-null  float64
 17  KURT_REL_RR        369289 non-null  float64
 18  SKEW_REL_RR        369289 non-null  float64
 19  uuid               369289 non-null  object
 20  uuid               369289 non-null  object
 21  VLF                369289 non-null  float64
 22  VLF_PCT            369289 non-null  float64
 23  LF                 369289 non-null  float64
 24  LF_PCT             369289 non-null  float64
 25  LF_NU              369289 non-null  float64
 26  HF                 369289 non-null  float64
 27  HF_PCT             369289 non-null  float64
 28  HF_NU              369289 non-null  float64
 29  TP                 369289 non-null  float64
 30  LF_HF              369289 non-null  float64
 31  HF_LF              369289 non-null  float64
 32  uuid               369289 non-null  object
 33  SD1                369289 non-null  float64
 34  SD2                369289 non-null  float64
 35  sampen             369289 non-null  float64
 36  higuci             369289 non-null  float64
 37  datasetId          369289 non-null  int64
 38  condition          369289 non-null  object
dtypes: float64(34), int64(1), object(4)
memory usage: 109.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41033 entries, 0 to 41032
Data columns (total 38 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   MEAN_RR            41033 non-null  float64
 1   MEDIAN_RR          41033 non-null  float64
 2   SDRR               41033 non-null  float64
 3   RMSSD              41033 non-null  float64
 4   SDSD               41033 non-null  float64
 5   SDRR_RMSSD         41033 non-null  float64
 6   pNN25              41033 non-null  float64
 7   pNN50              41033 non-null  float64
 8   KURT               41033 non-null  float64
 9   SKEW               41033 non-null  float64
 10  MEAN_REL_RR        41033 non-null  float64
 11  MEDIAN_REL_RR      41033 non-null  float64
 12  SDRR_REL_RR        41033 non-null  float64
 13  RMSSD_REL_RR       41033 non-null  float64
 14  SDSD_REL_RR        41033 non-null  float64
 15  SDRR_RMSSD_REL_RR  41033 non-null  float64
 16  KURT_REL_RR        41033 non-null  float64
 17  SKEW_REL_RR        41033 non-null  float64
 18  uuid               41033 non-null  object
 19  uuid               41033 non-null  object
 20  VLF                41033 non-null  float64
 21  VLF_PCT            41033 non-null  float64
 22  LF                 41033 non-null  float64
 23  LF_PCT             41033 non-null  float64
 24  LF_NU              41033 non-null  float64
 25  HF                 41033 non-null  float64
 26  HF_PCT             41033 non-null  float64
 27  HF_NU              41033 non-null  float64
 28  TP                 41033 non-null  float64
 29  LF_HF              41033 non-null  float64
 30  HF_LF              41033 non-null  float64
 31  uuid               41033 non-null  object
 32  SD1                41033 non-null  float64
 33  SD2                41033 non-null  float64
 34  sampen             41033 non-null  float64
 35  higuci             41033 non-null  float64
 36  datasetId          41033 non-null  int64
 37  condition          41033 non-null  object
dtypes: float64(33), int64(1), object(4)
memory usage: 11.9+ MB

In [17]:
label_train = LabelEncoder()
combined_train['condition'] = label_train.fit_transform(combined_train['condition'])

In [18]:
train_columns = set(combined_train.columns)
test_columns = set(combined_test.columns)

#columns that are in the training set but not in the test set
extra_columns_in_train = train_columns - test_columns


print("Columns in the training set but not in the test set:", extra_columns_in_train)

Columns in the training set but not in the test set: {'HR'}

In [19]:
combined_train = combined_train.drop(columns=['HR'])

In [20]:
df_train = combined_train

#the target label
label = ['condition']

#the features to be used for model training
features = ['MEAN_RR','RMSSD','pNN25','pNN50','LF','HF','LF_HF']

In [21]:
df_train[features].isnull().sum()

MEAN_RR    0
RMSSD      0
pNN25      0
pNN50      0
LF         0
HF         0
LF_HF      0
dtype: int64

In [22]:
scaler = StandardScaler()
scaler.fit(df_train[features])
df_train[features] = scaler.transform(df_train[features])

In [23]:
X = df_train[features].values
Y = df_train[label].values

In [24]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=40)

In [25]:
print(X_train.shape,Y_train.shape,X_test.shape,Y_test.shape)

(258502, 7) (258502, 1) (110787, 7) (110787, 1)

In [26]:
from sklearn.preprocessing import LabelEncoder
import tensorflow.keras as k

Y_train = k.utils.to_categorical(Y_train)
Y_test = k.utils.to_categorical(Y_test)

print("Shape y_train after one-hot encoding:", Y_train.shape)
print("Shape y_test after one-hot encoding:", Y_test.shape)

Shape y_train after one-hot encoding: (258502, 3)
Shape y_test after one-hot encoding: (110787, 3)

In [27]:
print(X_train.shape,Y_train.shape,X_test.shape,Y_test.shape)

(258502, 7) (258502, 3) (110787, 7) (110787, 3)

In [28]:
df_train.head()

,MEAN_RR,MEDIAN_RR,SDRR,RMSSD,SDSD,SDRR_RMSSD,pNN25,pNN50,KURT,SKEW,...,TP,LF_HF,HF_LF,uuid,SD1,SD2,sampen,higuci,datasetId,condition
0,0.309041,853.763730,140.972741,0.140024,15.553371,9.063146,0.157670,-0.335965,-0.856554,0.335218,...,3686.666157,-0.141218,0.015380,89df2855-56eb-4706-a23b-b39363dd605a,11.001565,199.061782,2.139754,1.163485,2,1
1,0.744562,948.357865,81.317742,-0.488516,12.964195,6.272369,-0.517493,-0.874583,-0.408190,-0.155286,...,3006.487251,0.585608,0.003055,80c795e4-aa56-4cc0-939c-19634b89cbb2,9.170129,114.634458,2.174499,1.084711,2,0
2,0.413598,907.006860,84.497236,0.322217,16.305274,5.182201,0.393570,-0.672601,0.351789,-0.656813,...,2685.879461,-0.060125,0.010607,c2d5d102-967c-487d-88f2-8b005a449f3e,11.533417,118.939253,2.135350,1.176315,2,0
3,0.281755,893.460030,90.370537,0.180299,15.720068,5.748591,0.239014,-0.739928,-0.504947,-0.386138,...,3434.520980,-0.168069,0.018074,37eabc44-1349-4040-8896-0d113ad4811f,11.119476,127.318597,2.178341,1.179688,2,1
4,-0.297140,811.184865,62.766242,1.028043,19.213657,3.266724,1.263959,-0.672601,-0.548408,-0.154252,...,2621.175204,-0.239679,0.033912,aa777a6a-7aa3-4f6e-aced-70f8691dd2b7,13.590641,87.718281,2.221121,1.249612,2,1

In [29]:
model = Sequential()

In [30]:
model.add(Dense(50, activation='relu', input_shape=(X_train.shape[1],)))

model.add(Dense(20, activation='relu'))

model.add(Dense(10, activation='relu'))

model.add(Dense(3, activation='softmax'))

c:\Users\Windows\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [31]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

history = model.fit(X_train, Y_train, validation_data=(X_test, Y_test), epochs=50, batch_size=1024, verbose=1)

Epoch 1/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.5840 - loss: 0.9028 - val_accuracy: 0.7147 - val_loss: 0.6917
Epoch 2/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7344 - loss: 0.6461 - val_accuracy: 0.7773 - val_loss: 0.5535
Epoch 3/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7864 - loss: 0.5269 - val_accuracy: 0.8087 - val_loss: 0.4686
Epoch 4/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8171 - loss: 0.4496 - val_accuracy: 0.8399 - val_loss: 0.4052
Epoch 5/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8465 - loss: 0.3890 - val_accuracy: 0.8598 - val_loss: 0.3628
Epoch 6/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8655 - loss: 0.3495 - val_accuracy: 0.8718 - val_loss: 0.3320
Epoch 7/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8783 - loss: 0.3213 - val_accuracy: 0.8847 - val_loss: 0.3078
Epoch 8/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8869 - loss: 0.3007 - val_accuracy: 0.8911 - val_loss: 0.2897
Epoch 9/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8939 - loss: 0.2828 - val_accuracy: 0.8952 - val_loss: 0.2742
Epoch 10/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8976 - loss: 0.2685 - val_accuracy: 0.9010 - val_loss: 0.2606
Epoch 11/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9056 - loss: 0.2540 - val_accuracy: 0.9117 - val_loss: 0.2440
Epoch 12/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9115 - loss: 0.2413 - val_accuracy: 0.9118 - val_loss: 0.2380
Epoch 13/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9168 - loss: 0.2294 - val_accuracy: 0.9188 - val_loss: 0.2222
Epoch 14/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9213 - loss: 0.2186 - val_accuracy: 0.9214 - val_loss: 0.2142
Epoch 15/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9237 - loss: 0.2098 - val_accuracy: 0.9238 - val_loss: 0.2096
Epoch 16/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9279 - loss: 0.2014 - val_accuracy: 0.9267 - val_loss: 0.2014
Epoch 17/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9295 - loss: 0.1968 - val_accuracy: 0.9286 - val_loss: 0.1989
Epoch 18/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9313 - loss: 0.1923 - val_accuracy: 0.9300 - val_loss: 0.1889
Epoch 19/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9334 - loss: 0.1849 - val_accuracy: 0.9348 - val_loss: 0.1797
Epoch 20/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9366 - loss: 0.1788 - val_accuracy: 0.9335 - val_loss: 0.1777
Epoch 21/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9381 - loss: 0.1729 - val_accuracy: 0.9366 - val_loss: 0.1739
Epoch 22/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9390 - loss: 0.1708 - val_accuracy: 0.9368 - val_loss: 0.1717
Epoch 23/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9411 - loss: 0.1653 - val_accuracy: 0.9405 - val_loss: 0.1644
Epoch 24/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9422 - loss: 0.1606 - val_accuracy: 0.9420 - val_loss: 0.1579
Epoch 25/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9429 - loss: 0.1583 - val_accuracy: 0.9419 - val_loss: 0.1580
Epoch 26/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9447 - loss: 0.1546 - val_accuracy: 0.9438 - val_loss: 0.1550
Epoch 27/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9457 - loss: 0.1520 - val_accuracy: 0.9431 - val_loss: 0.1554
Epoch 28/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9468 - loss: 0.1478 - val_accuracy: 0.9476 - val_loss: 0.1459
Epoch 29/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9479 - loss: 0.1457 - val_accuracy: 0.9492 - val_loss: 0.1429
Epoch 30/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9484 - loss: 0.1433 - val_accuracy: 0.9493 - val_loss: 0.1405
Epoch 31/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9493 - loss: 0.1399 - val_accuracy: 0.9475 - val_loss: 0.1428
Epoch 32/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9509 - loss: 0.1379 - val_accuracy: 0.9497 - val_loss: 0.1361
Epoch 33/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9520 - loss: 0.1347 - val_accuracy: 0.9518 - val_loss: 0.1346
Epoch 34/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9519 - loss: 0.1343 - val_accuracy: 0.9510 - val_loss: 0.1332
Epoch 35/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9528 - loss: 0.1314 - val_accuracy: 0.9519 - val_loss: 0.1335
Epoch 36/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9543 - loss: 0.1288 - val_accuracy: 0.9493 - val_loss: 0.1343
Epoch 37/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9531 - loss: 0.1288 - val_accuracy: 0.9537 - val_loss: 0.1269
Epoch 38/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9552 - loss: 0.1257 - val_accuracy: 0.9565 - val_loss: 0.1239
Epoch 39/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9557 - loss: 0.1241 - val_accuracy: 0.9483 - val_loss: 0.1348
Epoch 40/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9548 - loss: 0.1241 - val_accuracy: 0.9584 - val_loss: 0.1203
Epoch 41/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9572 - loss: 0.1195 - val_accuracy: 0.9570 - val_loss: 0.1197
Epoch 42/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9576 - loss: 0.1177 - val_accuracy: 0.9588 - val_loss: 0.1181
Epoch 43/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9577 - loss: 0.1174 - val_accuracy: 0.9538 - val_loss: 0.1226
Epoch 44/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9579 - loss: 0.1168 - val_accuracy: 0.9597 - val_loss: 0.1136
Epoch 45/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9595 - loss: 0.1134 - val_accuracy: 0.9587 - val_loss: 0.1160
Epoch 46/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9593 - loss: 0.1133 - val_accuracy: 0.9590 - val_loss: 0.1137
Epoch 47/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9607 - loss: 0.1103 - val_accuracy: 0.9598 - val_loss: 0.1154
Epoch 48/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9608 - loss: 0.1093 - val_accuracy: 0.9566 - val_loss: 0.1180
Epoch 49/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9611 - loss: 0.1090 - val_accuracy: 0.9598 - val_loss: 0.1085
Epoch 50/50
253/253 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9611 - loss: 0.1067 - val_accuracy: 0.9607 - val_loss: 0.1123

In [32]:
label_test = LabelEncoder()
combined_test['condition'] = label_test.fit_transform(combined_test['condition'])

In [33]:
df_test = combined_test
# the target label
label = ['condition']

# the features to be used for model training
features = ['MEAN_RR','RMSSD','pNN25','pNN50','LF','HF','LF_HF']

MEAN_RR: Average time between consecutive heartbeats, reflecting heart rate variability.
RMSSD: Square root of the mean of successive RR interval differences, indicating parasympathetic activity.
pNN25: Percentage of RR intervals differing by more than 25 ms, showing short-term heart rate variability.
pNN50: Percentage of RR intervals differing by more than 50 ms, reflecting parasympathetic tone.
LF: Power of the low-frequency band, representing both sympathetic and parasympathetic activity.
HF: Power of the high-frequency band, primarily reflecting parasympathetic activity.
LF_HF: Ratio of low to high-frequency power, indicating the balance between sympathetic and parasympathetic activity.

In [34]:
scaler = StandardScaler()
scaler.fit(df_test[features])
df_test[features] = scaler.transform(df_test[features])

In [35]:
X = df_test[features].values
Y = df_test[label].values

In [36]:
Y = k.utils.to_categorical(Y)

In [37]:
loss,acc = model.evaluate(X,Y,verbose=1)


print("Test Loss:", loss)
print("Test Accuracy:", acc)

1283/1283 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9613 - loss: 0.1128
Test Loss: 0.11396169662475586
Test Accuracy: 0.9609582424163818

In [38]:
#data = combined_test
#t = scaler.transform(pd.DataFrame(data[features].iloc[5545].values.reshape(1, -1), columns=features))
#print(t)

In [39]:
#Y_pred = model.predict(t)

In [40]:

X_test_combined = combined_test[features].values
Y_test_combined = combined_test[label].values

# Prediction
Y_pred_combined = model.predict(X_test_combined)

Y_pred_class_combined = np.argmax(Y_pred_combined, axis=1)
print(Y_pred_class_combined)

1283/1283 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
[1 1 1 ... 0 1 0]

In [41]:
print("Train Accuracy:", history.history['accuracy'][-1])
print("Validation Accuracy:", history.history['val_accuracy'][-1])

Train Accuracy: 0.9612150192260742
Validation Accuracy: 0.9607174396514893

In [42]:

model.save('stressprediction.keras')

In [43]:
#train_test = pd.concat([combined_train,combined_test], axis=1)
#train_test .head()

,MEAN_RR,MEDIAN_RR,SDRR,RMSSD,SDSD,SDRR_RMSSD,pNN25,pNN50,KURT,SKEW,...,TP,LF_HF,HF_LF,uuid,SD1,SD2,sampen,higuci,datasetId,condition
0,0.309041,853.763730,140.972741,0.140024,15.553371,9.063146,0.157670,-0.335965,-0.856554,0.335218,...,2442.168645,0.199605,0.005245,62b75db5-bc40-4c8f-9166-daf0efcab4c2,8.347898,115.862444,2.209659,1.100715,2.0,2.0
1,0.744562,948.357865,81.317742,-0.488516,12.964195,6.272369,-0.517493,-0.874583,-0.408190,-0.155286,...,2162.409316,-0.212028,0.025544,a99549ad-3eb6-4413-bc90-9053e7f7e684,14.542096,77.118903,2.186132,1.290615,2.0,1.0
2,0.413598,907.006860,84.497236,0.322217,16.305274,5.182201,0.393570,-0.672601,0.351789,-0.656813,...,2771.583978,-0.195937,0.022188,cb573d3a-c767-4556-b32e-ad8c08ded214,9.799336,125.044377,2.051571,1.226663,2.0,1.0
3,0.281755,893.460030,90.370537,0.180299,15.720068,5.748591,0.239014,-0.739928,-0.504947,-0.386138,...,6357.550689,-0.091277,0.011963,47a0c6de-2aef-4ac3-997d-252fa6fd07f1,11.639185,302.029812,2.080910,1.085143,2.0,2.0
4,-0.297140,811.184865,62.766242,1.028043,19.213657,3.266724,1.263959,-0.672601,-0.548408,-0.154252,...,1373.104689,-0.287959,0.089265,de3fd54f-c74e-4fe8-bf2a-7a127f68b312,7.266567,72.579248,2.068728,1.252547,2.0,0.0

In [44]:
#train_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 369289 entries, 0 to 369288
Data columns (total 76 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   MEAN_RR            369289 non-null  float64
 1   MEDIAN_RR          369289 non-null  float64
 2   SDRR               369289 non-null  float64
 3   RMSSD              369289 non-null  float64
 4   SDSD               369289 non-null  float64
 5   SDRR_RMSSD         369289 non-null  float64
 6   pNN25              369289 non-null  float64
 7   pNN50              369289 non-null  float64
 8   KURT               369289 non-null  float64
 9   SKEW               369289 non-null  float64
 10  MEAN_REL_RR        369289 non-null  float64
 11  MEDIAN_REL_RR      369289 non-null  float64
 12  SDRR_REL_RR        369289 non-null  float64
 13  RMSSD_REL_RR       369289 non-null  float64
 14  SDSD_REL_RR        369289 non-null  float64
 15  SDRR_RMSSD_REL_RR  369289 non-null  float64
 16  KURT_REL_RR        369289 non-null  float64
 17  SKEW_REL_RR        369289 non-null  float64
 18  uuid               369289 non-null  object
 19  uuid               369289 non-null  object
 20  VLF                369289 non-null  float64
 21  VLF_PCT            369289 non-null  float64
 22  LF                 369289 non-null  float64
 23  LF_PCT             369289 non-null  float64
 24  LF_NU              369289 non-null  float64
 25  HF                 369289 non-null  float64
 26  HF_PCT             369289 non-null  float64
 27  HF_NU              369289 non-null  float64
 28  TP                 369289 non-null  float64
 29  LF_HF              369289 non-null  float64
 30  HF_LF              369289 non-null  float64
 31  uuid               369289 non-null  object
 32  SD1                369289 non-null  float64
 33  SD2                369289 non-null  float64
 34  sampen             369289 non-null  float64
 35  higuci             369289 non-null  float64
 36  datasetId          369289 non-null  int64
 37  condition          369289 non-null  int32
 38  MEAN_RR            41033 non-null   float64
 39  MEDIAN_RR          41033 non-null   float64
 40  SDRR               41033 non-null   float64
 41  RMSSD              41033 non-null   float64
 42  SDSD               41033 non-null   float64
 43  SDRR_RMSSD         41033 non-null   float64
 44  pNN25              41033 non-null   float64
 45  pNN50              41033 non-null   float64
 46  KURT               41033 non-null   float64
 47  SKEW               41033 non-null   float64
 48  MEAN_REL_RR        41033 non-null   float64
 49  MEDIAN_REL_RR      41033 non-null   float64
 50  SDRR_REL_RR        41033 non-null   float64
 51  RMSSD_REL_RR       41033 non-null   float64
 52  SDSD_REL_RR        41033 non-null   float64
 53  SDRR_RMSSD_REL_RR  41033 non-null   float64
 54  KURT_REL_RR        41033 non-null   float64
 55  SKEW_REL_RR        41033 non-null   float64
 56  uuid               41033 non-null   object
 57  uuid               41033 non-null   object
 58  VLF                41033 non-null   float64
 59  VLF_PCT            41033 non-null   float64
 60  LF                 41033 non-null   float64
 61  LF_PCT             41033 non-null   float64
 62  LF_NU              41033 non-null   float64
 63  HF                 41033 non-null   float64
 64  HF_PCT             41033 non-null   float64
 65  HF_NU              41033 non-null   float64
 66  TP                 41033 non-null   float64
 67  LF_HF              41033 non-null   float64
 68  HF_LF              41033 non-null   float64
 69  uuid               41033 non-null   object
 70  SD1                41033 non-null   float64
 71  SD2                41033 non-null   float64
 72  sampen             41033 non-null   float64
 73  higuci             41033 non-null   float64
 74  datasetId          41033 non-null   float64
 75  condition          41033 non-null   float64
dtypes: float64(68), int32(1), int64(1), object(6)
memory usage: 212.7+ MB

In [45]:
#df_csv = pd.DataFrame(train_test)

# Convert DataFrame to CSV file
#df_csv.to_csv('output_file.csv', index=False)